# GenAI Tutorials

## Prelab: GenAI for Graphical Abstracts

### Activity 1 - Google Gemini

#### Part 1 - Generate Graphical Abstract

#### Instructions

1. Access Google Gemini via [gemini.google.com](https://gemini.google.com)
    - Gemini uses [Nano Banana](https://gemini.google/overview/image-generation) for image generation
1. Ask Gemini to generate an image using Prompt #1 (see below)
    - For Prompt #1, we start with the entire abstract from [Sleator 2008](https://pubmed.gov/19146522)
    - Preface this text with a specific ask: "Create a graphical abstract image based on the scientific abstract below:" 
1. Answer questions below

#### Questions

|1. Copy and paste your Prompt #1 in the box below.|
|:---|
| Prompt #1 |

|2. Copy and paste the generated image in the box below.|
|:--|
| Image #1 |

|3. Evaluate the graphical abstract that resulted from your Prompt #1.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| Did the image convey the content of the abstract well? Explain. | |
| Describe/critique the graphical abstract. | |
| What is one thing you would change about the graphical abstract? |

#### Part 2 - Adjust Style

#### Instructions

1. Identify aspects of style you may want to change about the resulting graphical abstract above, for example:
    - Lighter or darker background
    - More or less labels or text
    - Specific color changes
    - Other
1. Use the graphical abstract you created in Part 1 as input for Prompt #2, and engineer your prompt to also include style modifications of interest
1. Enter Prompt #2 to generate a second graphical abstract

Prompt# 2 Example: Modify the style of the above graphical abstract image by reducing dead space, making the image darker, and individual image parts bigger.

#### Questions

|1. Copy and paste your style-modifying Prompt #2 in the box below.|
|:---|
| Prompt #2 |

|2. Copy and paste the revised image in the box below.|
|:---|
| Image #2 |

|3. Evaluate the revised graphical abstract.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| How did the revised graphical abstract improve in quality, good and bad? | |
| What would you change to make this graphical abstract better? | |

#### Part 3 - Enhance Content

#### Instructions

1. Identify a detail that was not conveyed by the graphical abstract, but that interested you from your reading of the [Sleator 2008](https://pubmed.gov/19146522) review. 
    - e.g. Something conceptual: Metagenomics helps uncover unknown microbial diversity in a complex environment by circumventing the unculturability of most microbes. 
    - e.g. Something of niche focus: Something you learned about a specific environment mentioned, such as the Sargasso Sea was a good start for metagenomic inquiry because it contains a fairly simple microbial community.
1. Use the graphical abstract you created in the Part 2 as input for Prompt #3, and engineer your prompt to also include content addition of interest.
1. Enter Prompt #3 to generate a third graphical abstract.

Prompt #3 Example: Modify the above graphical abstract image by emphasizing that metagenomic approach can significantly enhance our understanding of the unknown microbial diversity in a complex environment by circumventing the unculturability of most microbes. 

#### Questions

|1. Copy and paste your content-modifying Prompt #3 into the box below.|
|:---|
| Prompt #3 |

|2. Copy and paste the second revised image in the box below.|
|:---|
| Image #3 |

|3. Evaluate the second revised graphical abstract.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| How did the second revised graphical abstract improve in quality, good and bad? | |
| What would you change to make this graphical abstract better? | |

### Activity 2 - Your Choice

#### Instructions

1. Access a different GenAI tool of your choice. Some suggestions include:
    - ChatGPT via [chatgpt.com](https://chatgpt.com)
    - Microsoft Copilot via [copilot.microsoft.com](https://copilot.microsoft.com)
        - Institutions like JHU [offer enterprise access](https://ctei.jhu.edu/teaching-and-ai) by signing in using "Continue with Microsoft" (e.g. username@jh.edu)
1. Generate one final graphical abstract using your **original** Prompt #1 from Activity 1.

#### Questions

|1. Which GenAI tool did you use in this activity?|
|:---|
| Tool |

|2. Copy and paste the image generated by a different tool in the box below.|
|:---|
| Image |

|3. Which of the two graphical abstracts better reflects the ideas in the paper and why?|
|:---|
| Answer |

### Grading Criteria

- Download as Microsoft Word (.docx) and upload on Canvas

### Footnotes

**Resources**

- [Google Doc](https://docs.google.com/document/d/1WOUwY9Mj9kYin-3YQ3Y5yDIjTXZecKhD)

**Contributions and Affiliations**

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: January 2026

## Project: GenAI for Graphical Abstracts

### Purpose

In this project, you will create the first panel of a Graphical Abstract (GA) for your research project work.
This GA building activity is meant to parallel your research project progress and to reflect your evolving ideas around the **key question** you want to address in your research, **datasets** you will use to answer your questions, and **methods** you will employ to do so.

See [Xue et al. 2023 Ballast Water Case Study](https://docs.google.com/document/d/15CMlsANhhU9Ck2_M069fg38GiKISR-aaUDcyHBN6Do8) example

### Learning Objectives

1. Create the first panel (Context) for a graphical abstract (Context/Methods/Findings)
1. Practice planning and critically evaluating GenAI

### Introduction

One framework for graphical abstracts is comprised of three panels

- **Context** – Introduce your question, datasets, samples, metadata
- **Method** – Snapshot of the Galaxy workflow you used to analyze data
- **Findings** - Summarize your main conclusion

Once you get to the end of the course, you will have all pieces together to put together a GA, and should use all tools available to you to do so - GenAI, manual figures, snapshots, etc. For the next five weeks of your project work phase, you will focus on **using GenAI for only the first panel** to convey the Context by integrating questions, datasets, samples, and metadata. 

A second goal is to practice prompt engineering - a fundamental AI literacy skill - to help develop stronger scientific communication skills. Prompting is a natural language skill and involves creating clear, contextual instructions (prompts) to guide AI models to perform tasks effectively.
By iteratively using GenAI to develop your GA, you have the opportunity to hone your scientific communication skills through improved prompts as you gain subject matter expertise (you are doing the research, you are the expert!)

### Activity 1 - Plan your prompt

*Estimated time: 5 min*

#### Instructions

1. Describe the topic you have proposed for your capstone project.
    a. Pick a research theme you want to explore (e.g. antibiotic resistance, pathogen detection, microbial diversity, microbes and disease, microbes of a specific environment, etc)
1. Describe the long-read datasets that you have identified for your topic.
    a. Identify a publicly available dataset you can analyze for your question. Aim for a dataset with clear metadata and a linked publication when possible.
1. Structure your prompts around the pillars of prompting which include:
    a. Task - a sentence that starts with an action (e.g. create, remake from scratch, modify, adjust, clarify, etc.)
        - "Create a graphical abstract"
    a. Format - structure of output (e.g. style of image)
        - "Create a graphical abstract ... with a simple style"
    a. Context - topic of interest, background info (e.g. datasets, sample metadata)

**Note**: It is fine to change your mind later and pursue a different dataset and/or a different topic; If you change your mind later, you can revise your approach in later GenAI project iterations 

#### Questions

|1. Write a draft research question. In 1-2 sentences, describe what you want to find out and why the dataset is a good fit.|
|:--------|
|<br>|

2. Identify key prompt 1 features.

| Prompt Feature | Your info (bullet points) |
|:--------|:-----|
| Task | |
| Format | |
| Context (Details) | |

### Activity 2 - Prepare Graphical Abstract

*Estimated time: 15 min*

#### Instructions

1. Using prompt text, generate GA using GenAI tool of your choice
1. Do as many attempts as can do in 15 min, logging each attempt’s prompt/output/evaluation

#### Questions

**Prompt #1, Graphical Abstract #1**

|1. Enter prompt text |
|:--------|
|<br>|

|2. Paste the resulting GA image below|
|:--------|
|<br>|

3. Evaluate GA output

| Evaluation | Your Answer |
| :--- | :--- |
| Provide overall description/critique of the GA output | |
| Name 2 specific things you would modify in the output GA | |

**Prompt #2, Graphical Abstract #2**

|1. Enter modified prompt text |
|:--------|
|<br>|

|2. Paste the resulting GA image below|
|:--------|
|<br>|

3. Evaluate GA output

| Evaluation | Your Answer |
| :--- | :--- |
| Provide overall description/critique of the GA output | |
| Name 2 specific things you would modify in the output GA | |

**Prompt #3, Graphical Abstract #3**

|1. Enter modified prompt text |
|:--------|
|<br>|

|2. Paste the resulting GA image below|
|:--------|
|<br>|

3. Evaluate GA output

| Evaluation | Your Answer |
| :--- | :--- |
| Provide overall description/critique of the GA output | |
| Name 2 specific things you would modify in the output GA | |

**Prompt #4, Graphical Abstract #4**

|1. Enter modified prompt text |
|:--------|
|<br>|

|2. Paste the resulting GA image below|
|:--------|
|<br>|

3. Evaluate GA output

| Evaluation | Your Answer |
| :--- | :--- |
| Provide overall description/critique of the GA output | |
| Name 2 specific things you would modify in the output GA | |

### Activity 3 - Reflect on your GenAI experience

*Estimated time: 5 min*

#### Instructions

1. Discuss your experience and outcomes in this Activity by answering questions below.

#### Questions

|1. What aspects of the graphical abstract were done well by GenAI?  Where did GenAI do poorly?|
|:--------|
|<br>|

|2. Was GenAI a helpful assistant for this activity?|
|:--------|
|<br>|

|3. Do you have concerns about using GenAI for this assignment?|
|:--------|
|<br>|

### Grading Criteria

- Download as Microsoft Word (.docx) and upload on Canvas

### Footnotes

**Resources**

- [Google Doc](https://docs.google.com/document/d/1BEQFZmkWbIj-SXNb4BBT6gtuclL0dvCR)

**Contributions and Affiliations**

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: February 2026
