# GenAI Tutorials

## Prelab: GenAI for Graphical Abstracts

### Activity 1 - Google Gemini

#### Part 1 - Generate Graphical Abstract

#### Instructions

1. Access Google Gemini via [gemini.google.com](https://gemini.google.com)
    - Gemini uses [Nano Banana](https://gemini.google/overview/image-generation) for image generation
1. Ask Gemini to generate an image using Prompt #1 (see below)
    - For Prompt #1, we start with the entire abstract from [Sleator 2008](https://pubmed.gov/19146522)
    - Preface this text with a specific ask: "Create a graphical abstract image based on the scientific abstract below:" 
1. Answer questions below

#### Questions

|1. Copy and paste your Prompt #1 in the box below.|
|:---|
| Prompt #1 |

|2. Copy and paste the generated image in the box below.|
|:--|
| Image #1 |

|3. Evaluate the graphical abstract that resulted from your Prompt #1.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| Did the image convey the content of the abstract well? Explain. | |
| Describe/critique the graphical abstract. | |
| What is one thing you would change about the graphical abstract? |

#### Part 2 - Adjust Style

#### Instructions

1. Identify aspects of style you may want to change about the resulting graphical abstract above, for example:
    - Lighter or darker background
    - More or less labels or text
    - Specific color changes
    - Other
1. Use the graphical abstract you created in Part 1 as input for Prompt #2, and engineer your prompt to also include style modifications of interest
1. Enter Prompt #2 to generate a second graphical abstract

Prompt# 2 Example: Modify the style of the above graphical abstract image by reducing dead space, making the image darker, and individual image parts bigger.

#### Questions

|1. Copy and paste your style-modifying Prompt #2 in the box below.|
|:---|
| Prompt #2 |

|2. Copy and paste the revised image in the box below.|
|:---|
| Image #2 |

|3. Evaluate the revised graphical abstract.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| How did the revised graphical abstract improve in quality, good and bad? | |
| What would you change to make this graphical abstract better? | |

#### Part 3 - Enhance Content

#### Instructions

1. Identify a detail that was not conveyed by the graphical abstract, but that interested you from your reading of the [Sleator 2008](https://pubmed.gov/19146522) review. 
    - e.g. Something conceptual: Metagenomics helps uncover unknown microbial diversity in a complex environment by circumventing the unculturability of most microbes. 
    - e.g. Something of niche focus: Something you learned about a specific environment mentioned, such as the Sargasso Sea was a good start for metagenomic inquiry because it contains a fairly simple microbial community.
1. Use the graphical abstract you created in the Part 2 as input for Prompt #3, and engineer your prompt to also include content addition of interest.
1. Enter Prompt #3 to generate a third graphical abstract.

Prompt #3 Example: Modify the above graphical abstract image by emphasizing that metagenomic approach can significantly enhance our understanding of the unknown microbial diversity in a complex environment by circumventing the unculturability of most microbes. 

#### Questions

|1. Copy and paste your content-modifying Prompt #3 into the box below.|
|:---|
| Prompt #3 |

|2. Copy and paste the second revised image in the box below.|
|:---|
| Image #3 |

|3. Evaluate the second revised graphical abstract.| |
| :--------- | :---------- |
| Evaluation | Your Answer |
| How did the second revised graphical abstract improve in quality, good and bad? | |
| What would you change to make this graphical abstract better? | |

### Activity 2 - Your Choice

#### Instructions

1. Access a different GenAI tool of your choice. Some suggestions include:
    - ChatGPT via [chatgpt.com](https://chatgpt.com)
    - Microsoft Copilot via [copilot.microsoft.com](https://copilot.microsoft.com)
        - Institutions like JHU [offer enterprise access](https://ctei.jhu.edu/teaching-and-ai) by signing in using "Continue with Microsoft" (e.g. username@jh.edu)
1. Generate one final graphical abstract using your **original** Prompt #1 from Activity 1.

#### Questions

|1. Which GenAI tool did you use in this activity?|
|:---|
| Tool |

|2. Copy and paste the image generated by a different tool in the box below.|
|:---|
| Image |

|3. Which of the two graphical abstracts better reflects the ideas in the paper and why?|
|:---|
| Answer |

### Grading Criteria

- Download as Microsoft Word (.docx) and upload on Canvas

### Footnotes

**Resources**

- [Google Doc](https://docs.google.com/document/d/1WOUwY9Mj9kYin-3YQ3Y5yDIjTXZecKhD)

**Contributions and Affiliations**

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: January 2026

## Project: GenAI for Graphical Abstracts

### Grading Criteria

- Download as Microsoft Word (.docx) and upload on Canvas

### Footnotes

**Resources**

- [Google Doc]()

**Contributions and Affiliations**

- Valeriya Gaysinskaya, Johns Hopkins University
- Frederick Tan, Johns Hopkins University

Last Revised: February 2026


